### ISSUE TITLE
ImageJ running out of memory

### ISSUE THREAD

**Issue by lbaltus** [neville-s-ng/ImageJ-BatchTools#1]
Hi,

I have been trying to use the Merge tool and it works fine on small batches, but I am starting to run out of working memory quickly on bigger batches. I believe it's because I use pretty big image files. Is it possible to adapt the code to close the images after they have been merged, before opening the new images? 

Thanks,
Lucas

**Comment by neville-s-ng** [comment]
Absolutely, will try to incorporate for next revision, thanks for picking up on that
I'll leave this open until it's addressed

**Comment by neville-s-ng** [comment]
Updated 0.98a 
Added option for merge to close files instead of only opening after completion
Also fixed issue with channel settings not working as intended
